Build incus.bin in doc/.readthedocs.yaml
since I got the following error while building on readthedocs.org
```
FileNotFoundError: [Errno 2] No such file or directory: '../incus.bin'
```

Signed-off-by: Hiroaki Nakamura <hnakamur@gmail.com>